services:
  app:
    build: .
    container_name: mirrorlog
    restart: unless-stopped
    expose:
      - 4001
    volumes:
      - ./logs:/mirror/mirrorlog/logs
      - ./config:/mirror/mirrorlog/config
    networks:
      - mirror
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 500M

networks:
  mirror:
    external: true
