services:
  logserver:
    build: .
    container_name: mirrorlog
    restart: unless-stopped
    ports:
      - "4001:4001"
    volumes:
      - ./logs:/mirrorlog/logs
      - ./config:/mirrorlog/config
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 500M
